# -*- coding: utf-8 -*-
"""simulate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVcq4fbzsjKoRPOjkopL1632vyetnYoo
"""
import pybullet as p
pass
